### PR TITLE
WIP: cleaning a bit the code

### PR DESCRIPTION
**Pull request by elegaanz**
Not sure it is so much better… but at least I tried. :grin: I wanted to do that before working on "real" issues. I think I will also setup ESLint to keep everything clean.

### CODE REVIEW

**Comment by elegaanz** [comment]
The git history is really dirty, I'll try to improve that…

**Comment by KillianKemps** [comment]
Thanks for cleaning the code!
Can you just fix up your commits and reduce them to only two? 
Like "Clean code of popup.js" and "CI: Use ESLint instead of Standard"

**Comment by elegaanz** [comment]
It should be OK now. :slightly_smiling_face:

**Review by KillianKemps — APPROVED** [review]
Thanks!

**Pull request merged**
