### PR TITLE
Webpack

### LINKED ISSUE #25: Pre-compile templates with Webpack
After having submitted the v0.3.0 of the plugin to validation at Firefox AMO, the review has rejected the plugin for the following reason:

```
This version did not pass the review because of the following issues:

1) The use of 'unsafe-eval' is not allowed in the manifest.json's CSP as it can cause major security issues.
```

We have to find a solution to remove this CSP rule

### PR DESCRIPTION
**Pull request by elegaanz**
I added Webpack. Now, we:
- Precompile templates with Webpack
- Use `.vue` files for views
- can use SCSS !

I also had to reorganize the files and to modify a little bit the tests to make them work.

Fix #25

### CODE REVIEW

**Comment by KillianKemps** [comment]
Thanks for you PR! :smiley: It's great that you are adding Webpack because I have to admit that I find Webpack complicated to configure.

I have checked out your branch, did `npm install`, `npm run build` and `npm run build:test` all seem to work well. I only wonder how you did with `npm test` because it raised this on my side: 
```
✖ 3792 problems (3792 errors, 0 warnings)    
```
Maybe, is it there some additional configuration to be done so it only checks our files and not the libraries?

I see there is no `manifest.json` in the generated `dist` folder. Can you configure Webpack in order to copy the `manifest.json` file and only have the relevant files to be packaged in the `dist` folder? For example, to remove the `tests.js` file because it is not needed for the plugin to work. Otherwise, Mozilla will reject the plugin during the review.

**Comment by elegaanz** [comment]
Do you have more details about the errors you are getting?

**Comment by KillianKemps** [comment]
Well, for the errors I get with `npm test` they are so long, I don't have anything else than lines like that:
```
  9611:1    error  Expected indentation of 2 spaces but found 0                                                                   indent                                                                             
  9611:13   error  Extra semicolon                                                                                                semi                                                                               
  9613:1    error  Block must not be padded by blank lines                                                                        padded-blocks                                                                      
  9613:5    error  Extra semicolon                                                                                                semi
```

I think it is the `./node_modules/.bin/eslint .` part of `npm test` which raises the issue

**Comment by elegaanz** [comment]
Yes, these messages comes from eslint. But normally you should have the path of the files from where these errors come.

**Comment by KillianKemps** [comment]
I can't go further up to see :D
screenshot from 2017-06-08 21-46-40

**Comment by KillianKemps** [comment]
Okay I changed the `"test"` line in the `package.json` to this:
```
    "test": "./node_modules/.bin/eslint lib/ test/ && npm run build:test && ./node_modules/.bin/mocha dist/tests.js"
```
So, it only tests our files. Do you think it's right or did I miss something?

**Comment by elegaanz** [comment]
Normally we have a `.eslintignore` file which avoid linting build files. The tests on Travis are passing without all these errors, it's strange. Maybe retry with the latest commit, and remove `node_modules` before running `npm i` again.

**Comment by KillianKemps** [comment]
So, I have removed the `node_modules`, `git pull`, did `npm i` then `npm test` and I have almost the same thing:
It first displays this for some seconds:
```
> Qowala-browser-plugin@ test /home/killian/Developpement/Projets/plugin-Qowala
> eslint . && ./node_modules/.bin/mocha build/tests/tests.js
```
And then it displays all the lines with an error, finished by this:
```
✖ 13360 problems (13360 errors, 0 warnings) 
```
So, I have now about 10 000 errors more than before.

Just for info, `node -v` returns `v6.9.1` and `npm --v` returns `3.10.8`

**Comment by elegaanz** [comment]
I have Node 7 with npm 4 on my computer, and it seems to be the same for Travis, so maybe you should update… It looks like you are using a globally installed `eslint`, do you have the same errors with the locally installed one?

**Comment by KillianKemps** [comment]
Ooookay, it works now.
Sorry, it was my fault, I had some other files in the directory too, and it may have tried to test them too ^^'

**Comment by KillianKemps** [comment]
It seems all very good! I just see that there are `.png` and a `manifest.json` files in the `build/tests` folder. Are they necessary? If then could you remove them?

**Comment by elegaanz** [comment]
The `.png` files are required by the views, themselves required by the tests (in fact they could run without these files, but Webpack consider they can't). The `manifest.json` is completely useless and I'll remove it.

**Review by KillianKemps — APPROVED** [review]
That was a great job! Thanks a lot!

**Comment by KillianKemps** [comment]
The plugin v0.3.1 has been submitted to AMO. We will seee if it goes through this time. :)

**Comment by KillianKemps** [comment]
The plugin has been approved and is now available! :tada:

**Pull request merged**
